<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Fastenshtein" Version="1.0.11"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3"/>
        <Reference Include="Discord.Net.Commands">
            <HintPath>..\..\..\..\..\.nuget\packages\discord.net.commands\3.16.0\lib\net6.0\Discord.Net.Commands.dll</HintPath>
        </Reference>
        <Reference Include="Discord.Net.Core">
            <HintPath>..\..\..\..\..\.nuget\packages\discord.net.core\3.16.0\lib\net6.0\Discord.Net.Core.dll</HintPath>
        </Reference>
        <Reference Include="Discord.Net.Rest">
            <HintPath>..\..\..\..\..\.nuget\packages\discord.net.rest\3.16.0\lib\net6.0\Discord.Net.Rest.dll</HintPath>
        </Reference>
        <Reference Include="Discord.Net.WebSocket">
            <HintPath>..\..\..\..\..\.nuget\packages\discord.net.websocket\3.16.0\lib\net6.0\Discord.Net.WebSocket.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\FoodBot.Application\FoodBot.Application.csproj"/>
        <ProjectReference Include="..\..\FoodBot.Infrastructure\FoodBot.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
