<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>FoodBot.Api</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FoodBot.Application\FoodBot.Application.csproj"/>
        <ProjectReference Include="..\FoodBot.Infrastructure\FoodBot.Infrastructure.csproj"/>
        <None Include="../Data/*">
            <Link>Data\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <TargetPath>Data\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
